Feature/recurring rent transactions
Jacu93/nowak-shared-rent pull request #15
Opened 2020-02-17 23:28 UTC by Jacu93

It's been a while since last pull request and for that reason I'd like to close this part already :D Just as a quick reminder this branch introduces recurring monthly payments without need of an actual scheduler. Main feature is balance presentation on the dashboard. You can see last 2 months balance for each tenant. Balance for each month is the total amount from transactions split among all tenants plus rent value (also split). Everytime new rent value is defined it will be charged next month.

I think that all improvements I still have to do are listed here:
https://docs.google.com/document/d/14g8G9dr_y50B8FHUGLYVBBThs0iBfc_VN79tngBzc40/edit
but I think it will be the best to move them onto new branch. Please share your opinion.

2020-02-24 15:37 UTC, piekaa requested changes
Sure, move improvements to another branch. Let's do small steps.

2020-02-24 15:37 UTC, piekaa commented on src/main/java/com/piekoszek/nowaksharedrent/transactions/TransactionsController.java
>              return new ResponseEntity<>(new MessageResponse("No transactions with given id found."), HttpStatus.BAD_REQUEST);
I know it was not changed, but NOT_FOUND fits better.

2020-02-24 15:37 UTC, piekaa commented on src/main/java/com/piekoszek/nowaksharedrent/transactions/TransactionsServiceImpl.java
> +    public Map<String, Set<Payer>> getLastMonthsBalance(String apartmentId) {
rename to getLastTwoMonthsBalance or parametrize

2020-02-24 15:37 UTC, piekaa commented on src/main/java/com/piekoszek/nowaksharedrent/apartment/ApartmentServiceImpl.java
> +        if (currDate.get(Calendar.MONTH) == Calendar.DECEMBER) {
I think without this if - else it would be better (rent would be set for current month).

2020-02-24 15:37 UTC, piekaa commented on src/main/resources/static/scripts/homePage.js
> +            while (rentsArrayLength>0) {
`for(i = rentsArrayLength ; i >=0 ; i--)`

2020-02-24 15:37 UTC, piekaa commented on src/main/resources/static/scripts/homePage.js
> +                    rentsArrayLength = 0;
`break;`

2020-02-24 15:37 UTC, piekaa commented on src/main/resources/static/scripts/transactionsPage.js
>          $('.datepicker').datepicker({
assign $('.datepicker') to variable and reuse

2020-02-24 15:38 UTC, piekaa commented
Also remember to change loop in then: in TransactionsServiceTest

2020-03-01 23:07 UTC, Jacu93 commented on src/main/java/com/piekoszek/nowaksharedrent/apartment/ApartmentServiceImpl.java
> +        if (currDate.get(Calendar.MONTH) == Calendar.DECEMBER) {
Rent values are stored in order as you add them anyway but in the feature I might add just the timestamp so it is certain which value is the last. I have to make sure that beginning of the month doesn't matter in the rest of the code.

2020-03-03 23:19 UTC, Jacu93 commented
Corrections done as requested

2020-03-04 20:07 UTC, piekaa approved these changes
🥇

2020-03-04 20:07 UTC, piekaa commented on src/main/resources/static/scripts/homePage.js
> +            for(i = rentsArrayLength ; i >=0 ; i--) {
could be let i, but nvm, just tip for future

2020-03-04 22:14 UTC, merged